// Code generated by MockGen. DO NOT EDIT.
// Source: git.workshop21.ch/go/abraxas/tracing (interfaces: Tracing)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	tracing "git.workshop21.ch/go/abraxas/tracing"
	gomock "github.com/golang/mock/gomock"
	http "net/http"
	reflect "reflect"
)

// MockTracing is a mock of Tracing interface
type MockTracing struct {
	ctrl     *gomock.Controller
	recorder *MockTracingMockRecorder
}

// MockTracingMockRecorder is the mock recorder for MockTracing
type MockTracingMockRecorder struct {
	mock *MockTracing
}

// NewMockTracing creates a new mock instance
func NewMockTracing(ctrl *gomock.Controller) *MockTracing {
	mock := &MockTracing{ctrl: ctrl}
	mock.recorder = &MockTracingMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockTracing) EXPECT() *MockTracingMockRecorder {
	return m.recorder
}

// NewClientInterceptorSpan mocks base method
func (m *MockTracing) NewClientInterceptorSpan(arg0 context.Context, arg1 string) (context.Context, *tracing.Span) {
	ret := m.ctrl.Call(m, "NewClientInterceptorSpan", arg0, arg1)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(*tracing.Span)
	return ret0, ret1
}

// NewClientInterceptorSpan indicates an expected call of NewClientInterceptorSpan
func (mr *MockTracingMockRecorder) NewClientInterceptorSpan(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewClientInterceptorSpan", reflect.TypeOf((*MockTracing)(nil).NewClientInterceptorSpan), arg0, arg1)
}

// NewClientSpan mocks base method
func (m *MockTracing) NewClientSpan(arg0 context.Context, arg1, arg2 string) (context.Context, *tracing.Span) {
	ret := m.ctrl.Call(m, "NewClientSpan", arg0, arg1, arg2)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(*tracing.Span)
	return ret0, ret1
}

// NewClientSpan indicates an expected call of NewClientSpan
func (mr *MockTracingMockRecorder) NewClientSpan(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewClientSpan", reflect.TypeOf((*MockTracing)(nil).NewClientSpan), arg0, arg1, arg2)
}

// NewServerInterceptorSpan mocks base method
func (m *MockTracing) NewServerInterceptorSpan(arg0 context.Context, arg1 string) (context.Context, *tracing.Span) {
	ret := m.ctrl.Call(m, "NewServerInterceptorSpan", arg0, arg1)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(*tracing.Span)
	return ret0, ret1
}

// NewServerInterceptorSpan indicates an expected call of NewServerInterceptorSpan
func (mr *MockTracingMockRecorder) NewServerInterceptorSpan(arg0, arg1 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewServerInterceptorSpan", reflect.TypeOf((*MockTracing)(nil).NewServerInterceptorSpan), arg0, arg1)
}

// NewServerSpan mocks base method
func (m *MockTracing) NewServerSpan(arg0 context.Context, arg1, arg2 string) (context.Context, *tracing.Span) {
	ret := m.ctrl.Call(m, "NewServerSpan", arg0, arg1, arg2)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(*tracing.Span)
	return ret0, ret1
}

// NewServerSpan indicates an expected call of NewServerSpan
func (mr *MockTracingMockRecorder) NewServerSpan(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewServerSpan", reflect.TypeOf((*MockTracing)(nil).NewServerSpan), arg0, arg1, arg2)
}

// NewSpan mocks base method
func (m *MockTracing) NewSpan(arg0 context.Context, arg1, arg2 string) (context.Context, *tracing.Span) {
	ret := m.ctrl.Call(m, "NewSpan", arg0, arg1, arg2)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(*tracing.Span)
	return ret0, ret1
}

// NewSpan indicates an expected call of NewSpan
func (mr *MockTracingMockRecorder) NewSpan(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSpan", reflect.TypeOf((*MockTracing)(nil).NewSpan), arg0, arg1, arg2)
}

// NewSpanHTTP mocks base method
func (m *MockTracing) NewSpanHTTP(arg0 *http.Request, arg1, arg2 string) (*http.Request, *tracing.Span) {
	ret := m.ctrl.Call(m, "NewSpanHTTP", arg0, arg1, arg2)
	ret0, _ := ret[0].(*http.Request)
	ret1, _ := ret[1].(*tracing.Span)
	return ret0, ret1
}

// NewSpanHTTP indicates an expected call of NewSpanHTTP
func (mr *MockTracingMockRecorder) NewSpanHTTP(arg0, arg1, arg2 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewSpanHTTP", reflect.TypeOf((*MockTracing)(nil).NewSpanHTTP), arg0, arg1, arg2)
}
